--- #YAML:1.0
name: WWW-Restaurant-Menu
version: 0.1
author:
  - Julian Mehnle <julian@mehnle.net>
abstract: |-
  An abstract Perl base class for querying online menus
  of restaurants.
license: perl
requires:
  perl: 5.8
recommends:
  Encode: 0
  HTML::HeadParser: 0
  HTML::TableExtract: 0
  HTML::TableExtract::Raw: 0
  LWP: 0
provides:
  WWW::Restaurant::DE::Munich::Edison::Menu::Lunch:
    file: lib/WWW/Restaurant/DE/Munich/Edison/Menu/Lunch.pm
    version: 0.1
  WWW::Restaurant::Menu:
    file: lib/WWW/Restaurant/Menu.pm
    version: 0.1
  WWW::Restaurant::Menu::Item:
    file: lib/WWW/Restaurant/Menu/Item.pm
    version: 0.1
  WWW::Restaurant::Menu::Item::Dessert:
    file: lib/WWW/Restaurant/Menu/Item.pm
    version: 0.1
  WWW::Restaurant::Menu::Item::Drink:
    file: lib/WWW/Restaurant/Menu/Item.pm
    version: 0.1
  WWW::Restaurant::Menu::Item::Meal:
    file: lib/WWW/Restaurant/Menu/Item.pm
    version: 0.1
  WWW::Restaurant::Menu::Item::Starter:
    file: lib/WWW/Restaurant/Menu/Item.pm
    version: 0.1
generated_by: Module::Build version 0.24
